cmake_minimum_required(VERSION 4.3)
project(LearnCPP)


set(CMAKE_CXX_STANDARD 20)

add_executable(LearnCPP v0/helloworld.cpp
        v0/helloworld.cpp
        v0/helloworld.cpp
        v0/PrintStandard.cpp
        Variables.cpp
        Variables.cpp
        InitialisationType.cpp
        ListInitialisation.cpp
        MaybeUnused.cpp)
