cmake_minimum_required(VERSION 4.3)
project(LearnCPP)


set(CMAKE_CXX_STANDARD 20)

add_executable(LearnCPP c0/helloworld.cpp
        c0/helloworld.cpp
        c0/helloworld.cpp
        c0/PrintStandard.cpp
        c1/Variables.cpp
        c1/Variables.cpp
        c1/InitialisationType.cpp
        c1/ListInitialisation.cpp
        c1/MaybeUnused.cpp
        c1/cout.cpp
        c1/cin.cpp
        c1/buffering.cpp
        c1/LiteralsVariables.cpp
        c1/Expression.cpp
        c1/FirstProgram.cpp
        c1/ChapterFinalQuizz.cpp
        c1/ChapterFinalQuizz.cpp
        c2/intro_2_func.cpp
        c2/function_within_function.cpp
        c2/return_value.cpp
        c2/status_codes.cpp
        c2/void_function.cpp
        c2/void_function2.cpp
        c2/function_arguments.cpp
        c2/function_arguments2.cpp
        c2/unamned_aprameter.cpp
        c2/local_var.cpp
        c2/scope.cpp
        c2/forward_declaration.cpp
        c2/Diff_Files/input.cpp
        c2/Diff_Files/main.cpp
)
